using RGB.NET.Core;
using System.Collections.Generic;

namespace Artemis.DataModelExpansions.LogitechWrapper.Services
{
    internal static class LedMapping
    {
        internal static readonly Dictionary<LogitechLedId, LedId> LedNames = new()
        {
            { LogitechLedId.ESC, LedId.Keyboard_Escape },
            { LogitechLedId.F1, LedId.Keyboard_F1 },
            { LogitechLedId.F2, LedId.Keyboard_F2 },
            { LogitechLedId.F3, LedId.Keyboard_F3 },
            { LogitechLedId.F4, LedId.Keyboard_F4 },
            { LogitechLedId.F5, LedId.Keyboard_F5 },
            { LogitechLedId.F6, LedId.Keyboard_F6 },
            { LogitechLedId.F7, LedId.Keyboard_F7 },
            { LogitechLedId.F8, LedId.Keyboard_F8 },
            { LogitechLedId.F9, LedId.Keyboard_F9 },
            { LogitechLedId.F10, LedId.Keyboard_F10 },
            { LogitechLedId.F11, LedId.Keyboard_F11 },
            { LogitechLedId.TILDE, LedId.Keyboard_GraveAccentAndTilde },
            { LogitechLedId.ONE, LedId.Keyboard_1 },
            { LogitechLedId.TWO, LedId.Keyboard_2 },
            { LogitechLedId.THREE, LedId.Keyboard_3 },
            { LogitechLedId.FOUR, LedId.Keyboard_4 },
            { LogitechLedId.FIVE, LedId.Keyboard_5 },
            { LogitechLedId.SIX, LedId.Keyboard_6 },
            { LogitechLedId.SEVEN, LedId.Keyboard_7 },
            { LogitechLedId.EIGHT, LedId.Keyboard_8 },
            { LogitechLedId.NINE, LedId.Keyboard_9 },
            { LogitechLedId.ZERO, LedId.Keyboard_0 },
            { LogitechLedId.MINUS, LedId.Keyboard_MinusAndUnderscore },
            { LogitechLedId.TAB, LedId.Keyboard_Tab },
            { LogitechLedId.Q, LedId.Keyboard_Q },
            { LogitechLedId.W, LedId.Keyboard_W },
            { LogitechLedId.E, LedId.Keyboard_E },
            { LogitechLedId.R, LedId.Keyboard_R },
            { LogitechLedId.T, LedId.Keyboard_T },
            { LogitechLedId.Y, LedId.Keyboard_Y },
            { LogitechLedId.U, LedId.Keyboard_U },
            { LogitechLedId.I, LedId.Keyboard_I },
            { LogitechLedId.O, LedId.Keyboard_O },
            { LogitechLedId.P, LedId.Keyboard_P },
            { LogitechLedId.OPEN_BRACKET, LedId.Keyboard_BracketLeft },
            { LogitechLedId.CAPS_LOCK, LedId.Keyboard_CapsLock },
            { LogitechLedId.A, LedId.Keyboard_A },
            { LogitechLedId.S, LedId.Keyboard_S },
            { LogitechLedId.D, LedId.Keyboard_D },
            { LogitechLedId.F, LedId.Keyboard_F },
            { LogitechLedId.G, LedId.Keyboard_G },
            { LogitechLedId.H, LedId.Keyboard_H },
            { LogitechLedId.J, LedId.Keyboard_J },
            { LogitechLedId.K, LedId.Keyboard_K },
            { LogitechLedId.L, LedId.Keyboard_L },
            { LogitechLedId.SEMICOLON, LedId.Keyboard_SemicolonAndColon },
            { LogitechLedId.APOSTROPHE, LedId.Keyboard_ApostropheAndDoubleQuote },
            { LogitechLedId.LEFT_SHIFT, LedId.Keyboard_LeftShift },
            { LogitechLedId.Z, LedId.Keyboard_Z },
            { LogitechLedId.X, LedId.Keyboard_X },
            { LogitechLedId.C, LedId.Keyboard_C },
            { LogitechLedId.V, LedId.Keyboard_V },
            { LogitechLedId.B, LedId.Keyboard_B },
            { LogitechLedId.N, LedId.Keyboard_N },
            { LogitechLedId.M, LedId.Keyboard_M },
            { LogitechLedId.COMMA, LedId.Keyboard_CommaAndLessThan },
            { LogitechLedId.PERIOD, LedId.Keyboard_PeriodAndBiggerThan },
            { LogitechLedId.FORWARD_SLASH, LedId.Keyboard_SlashAndQuestionMark },
            { LogitechLedId.LEFT_CONTROL, LedId.Keyboard_LeftCtrl },
            { LogitechLedId.LEFT_WINDOWS, LedId.Keyboard_LeftGui },
            { LogitechLedId.LEFT_ALT, LedId.Keyboard_LeftAlt },
            { LogitechLedId.SPACE, LedId.Keyboard_Space },
            { LogitechLedId.RIGHT_ALT, LedId.Keyboard_RightAlt },
            { LogitechLedId.RIGHT_WINDOWS, LedId.Keyboard_RightGui },
            { LogitechLedId.APPLICATION_SELECT, LedId.Keyboard_Application },
            { LogitechLedId.F12, LedId.Keyboard_F12 },
            { LogitechLedId.PRINT_SCREEN, LedId.Keyboard_PrintScreen },
            { LogitechLedId.SCROLL_LOCK, LedId.Keyboard_ScrollLock },
            { LogitechLedId.PAUSE_BREAK, LedId.Keyboard_PauseBreak },
            { LogitechLedId.INSERT, LedId.Keyboard_Insert },
            { LogitechLedId.HOME, LedId.Keyboard_Home },
            { LogitechLedId.PAGE_UP, LedId.Keyboard_PageUp },
            { LogitechLedId.CLOSE_BRACKET, LedId.Keyboard_BracketRight },
            { LogitechLedId.BACKSLASH, LedId.Keyboard_NonUsBackslash },
            //{ LogitechLedId.TILDE, LedId.Keyboard_NonUsTilde },
            { LogitechLedId.ENTER, LedId.Keyboard_Enter },
            { LogitechLedId.EQUALS, LedId.Keyboard_EqualsAndPlus },
            { LogitechLedId.BACKSPACE, LedId.Keyboard_Backspace },
            { LogitechLedId.KEYBOARD_DELETE, LedId.Keyboard_Delete },
            { LogitechLedId.END, LedId.Keyboard_End },
            { LogitechLedId.PAGE_DOWN, LedId.Keyboard_PageDown },
            { LogitechLedId.RIGHT_SHIFT, LedId.Keyboard_RightShift },
            { LogitechLedId.RIGHT_CONTROL, LedId.Keyboard_RightCtrl },
            { LogitechLedId.ARROW_UP, LedId.Keyboard_ArrowUp },
            { LogitechLedId.ARROW_LEFT, LedId.Keyboard_ArrowLeft },
            { LogitechLedId.ARROW_DOWN, LedId.Keyboard_ArrowDown },
            { LogitechLedId.ARROW_RIGHT, LedId.Keyboard_ArrowRight },
            { LogitechLedId.NUM_LOCK, LedId.Keyboard_NumLock },
            { LogitechLedId.NUM_SLASH, LedId.Keyboard_NumSlash },
            { LogitechLedId.NUM_ASTERISK, LedId.Keyboard_NumAsterisk },
            { LogitechLedId.NUM_MINUS, LedId.Keyboard_NumMinus },
            { LogitechLedId.NUM_PLUS, LedId.Keyboard_NumPlus },
            { LogitechLedId.NUM_ENTER, LedId.Keyboard_NumEnter },
            { LogitechLedId.NUM_SEVEN, LedId.Keyboard_Num7 },
            { LogitechLedId.NUM_EIGHT, LedId.Keyboard_Num8 },
            { LogitechLedId.NUM_NINE, LedId.Keyboard_Num9 },
            { LogitechLedId.NUM_FOUR, LedId.Keyboard_Num4 },
            { LogitechLedId.NUM_FIVE, LedId.Keyboard_Num5 },
            { LogitechLedId.NUM_SIX, LedId.Keyboard_Num6 },
            { LogitechLedId.NUM_ONE, LedId.Keyboard_Num1 },
            { LogitechLedId.NUM_TWO, LedId.Keyboard_Num2 },
            { LogitechLedId.NUM_THREE, LedId.Keyboard_Num3 },
            { LogitechLedId.NUM_ZERO, LedId.Keyboard_Num0 },
            { LogitechLedId.NUM_PERIOD, LedId.Keyboard_NumPeriodAndDelete },
            { LogitechLedId.G_1, LedId.Keyboard_Programmable1 },
            { LogitechLedId.G_2, LedId.Keyboard_Programmable2 },
            { LogitechLedId.G_3, LedId.Keyboard_Programmable3 },
            { LogitechLedId.G_4, LedId.Keyboard_Programmable4 },
            { LogitechLedId.G_5, LedId.Keyboard_Programmable5 },
            { LogitechLedId.G_6, LedId.Keyboard_Programmable6 },
            { LogitechLedId.G_7, LedId.Keyboard_Programmable7 },
            { LogitechLedId.G_8, LedId.Keyboard_Programmable8 },
            { LogitechLedId.G_9, LedId.Keyboard_Programmable9 },
            { LogitechLedId.G_LOGO, LedId.Logo },
            { LogitechLedId.G_BADGE, LedId.Keyboard_Custom1 },
        };

        internal static readonly Dictionary<LogitechLedId, int> BitmapMap = new()
        {
            [LogitechLedId.ESC] = 0,
            [LogitechLedId.F1] = 4,
            [LogitechLedId.F2] = 8,
            [LogitechLedId.F3] = 12,
            [LogitechLedId.F4] = 16,
            [LogitechLedId.F5] = 20,
            [LogitechLedId.F6] = 24,
            [LogitechLedId.F7] = 28,
            [LogitechLedId.F8] = 32,
            [LogitechLedId.F9] = 36,
            [LogitechLedId.F10] = 40,
            [LogitechLedId.F11] = 44,
            [LogitechLedId.F12] = 48,
            [LogitechLedId.PRINT_SCREEN] = 52,
            [LogitechLedId.SCROLL_LOCK] = 56,
            [LogitechLedId.PAUSE_BREAK] = 60,
            //64
            //68
            //72
            //76
            //80
            [LogitechLedId.TILDE] = 84,
            [LogitechLedId.ONE] = 88,
            [LogitechLedId.TWO] = 92,
            [LogitechLedId.THREE] = 96,
            [LogitechLedId.FOUR] = 100,
            [LogitechLedId.FIVE] = 104,
            [LogitechLedId.SIX] = 108,
            [LogitechLedId.SEVEN] = 112,
            [LogitechLedId.EIGHT] = 116,
            [LogitechLedId.NINE] = 120,
            [LogitechLedId.ZERO] = 124,
            [LogitechLedId.MINUS] = 128,
            [LogitechLedId.EQUALS] = 132,
            [LogitechLedId.BACKSPACE] = 136,
            [LogitechLedId.INSERT] = 140,
            [LogitechLedId.HOME] = 144,
            [LogitechLedId.PAGE_UP] = 148,
            [LogitechLedId.NUM_LOCK] = 152,
            [LogitechLedId.NUM_SLASH] = 156,
            [LogitechLedId.NUM_ASTERISK] = 160,
            [LogitechLedId.NUM_MINUS] = 164,
            [LogitechLedId.TAB] = 168,
            [LogitechLedId.Q] = 172,
            [LogitechLedId.W] = 176,
            [LogitechLedId.E] = 180,
            [LogitechLedId.R] = 184,
            [LogitechLedId.T] = 188,
            [LogitechLedId.Y] = 192,
            [LogitechLedId.U] = 196,
            [LogitechLedId.I] = 200,
            [LogitechLedId.O] = 204,
            [LogitechLedId.P] = 208,
            [LogitechLedId.OPEN_BRACKET] = 212,
            [LogitechLedId.CLOSE_BRACKET] = 216,
            [LogitechLedId.BACKSLASH] = 220,
            [LogitechLedId.KEYBOARD_DELETE] = 224,
            [LogitechLedId.END] = 228,
            [LogitechLedId.PAGE_DOWN] = 232,
            [LogitechLedId.NUM_SEVEN] = 236,
            [LogitechLedId.NUM_EIGHT] = 240,
            [LogitechLedId.NUM_NINE] = 244,
            [LogitechLedId.NUM_PLUS] = 248,
            [LogitechLedId.CAPS_LOCK] = 252,
            [LogitechLedId.A] = 256,
            [LogitechLedId.S] = 260,
            [LogitechLedId.D] = 264,
            [LogitechLedId.F] = 268,
            [LogitechLedId.G] = 272,
            [LogitechLedId.H] = 276,
            [LogitechLedId.J] = 280,
            [LogitechLedId.K] = 284,
            [LogitechLedId.L] = 288,
            [LogitechLedId.SEMICOLON] = 292,
            [LogitechLedId.APOSTROPHE] = 296,
            //[LogitechLedId.HASHTAG] = 300,
            [LogitechLedId.ENTER] = 304,
            //308
            //312
            //316
            [LogitechLedId.NUM_FOUR] = 320,
            [LogitechLedId.NUM_FIVE] = 324,
            [LogitechLedId.NUM_SIX] = 328,
            //332
            [LogitechLedId.LEFT_SHIFT] = 336,
            //[LogitechLedId.BACKSLASH_UK] = 340,
            [LogitechLedId.Z] = 344,
            [LogitechLedId.X] = 348,
            [LogitechLedId.C] = 352,
            [LogitechLedId.V] = 356,
            [LogitechLedId.B] = 360,
            [LogitechLedId.N] = 364,
            [LogitechLedId.M] = 368,
            [LogitechLedId.COMMA] = 372,
            [LogitechLedId.PERIOD] = 376,
            [LogitechLedId.FORWARD_SLASH] = 380,
            //[LogitechLedId.OEM102] = 384,
            [LogitechLedId.RIGHT_SHIFT] = 388,
            //392
            [LogitechLedId.ARROW_UP] = 396,
            //400
            [LogitechLedId.NUM_ONE] = 404,
            [LogitechLedId.NUM_TWO] = 408,
            [LogitechLedId.NUM_THREE] = 412,
            [LogitechLedId.NUM_ENTER] = 416,
            [LogitechLedId.LEFT_CONTROL] = 420,
            [LogitechLedId.LEFT_WINDOWS] = 424,
            [LogitechLedId.LEFT_ALT] = 428,
            //432
            //[LogitechLedId.JPN_MUHENKAN] = 436,
            [LogitechLedId.SPACE] = 440,
            //444
            //448
            //[LogitechLedId.JPN_HENKAN] = 452,
            //[LogitechLedId.JPN_HIRAGANA_KATAKANA] = 456,
            //460
            [LogitechLedId.RIGHT_ALT] = 464,
            [LogitechLedId.RIGHT_WINDOWS] = 468,
            [LogitechLedId.APPLICATION_SELECT] = 472,
            [LogitechLedId.RIGHT_CONTROL] = 476,
            [LogitechLedId.ARROW_LEFT] = 480,
            [LogitechLedId.ARROW_DOWN] = 484,
            [LogitechLedId.ARROW_RIGHT] = 488,
            [LogitechLedId.NUM_ZERO] = 492,
            [LogitechLedId.NUM_PERIOD] = 496,
            //500
        };

        internal static readonly Dictionary<ScanCode, int> ScanCoded = new()
        {
            [ScanCode.KEY_ESC] = 0,
            [ScanCode.KEY_F1] = 4,
            [ScanCode.KEY_F2] = 8,
            [ScanCode.KEY_F3] = 12,
            [ScanCode.KEY_F4] = 16,
            [ScanCode.KEY_F5] = 20,
            [ScanCode.KEY_F6] = 24,
            [ScanCode.KEY_F7] = 28,
            [ScanCode.KEY_F8] = 32,
            [ScanCode.KEY_F9] = 26,
            [ScanCode.KEY_F10] = 40,
            [ScanCode.KEY_F11] = 44,
            [ScanCode.KEY_F12] = 48,
            [ScanCode.KEY_SYSRQ] = 52,
            [ScanCode.KEY_SCROLLLOCK] = 56,
            [ScanCode.KEY_PAUSE] = 60,

            [ScanCode.KEY_GRAVE] = 84,
            [ScanCode.KEY_1] = 88,
            [ScanCode.KEY_2] = 92,
            [ScanCode.KEY_3] = 96,
            [ScanCode.KEY_4] = 100,
            [ScanCode.KEY_5] = 104,
            [ScanCode.KEY_6] = 108,
            [ScanCode.KEY_7] = 112,
            [ScanCode.KEY_8] = 116,
            [ScanCode.KEY_9] = 120,
            [ScanCode.KEY_0] = 124,
            [ScanCode.KEY_MINUS] = 128,
            [ScanCode.KEY_EQUAL] = 132,
            [ScanCode.KEY_BACKSPACE] = 136,
            [ScanCode.KEY_INSERT] = 140,
            [ScanCode.KEY_HOME] = 144,
            [ScanCode.KEY_PAGEUP] = 148,
            [ScanCode.KEY_NUMLOCK] = 152,
            [ScanCode.KEY_KPSLASH] = 156,
            [ScanCode.KEY_KPASTERISK] = 160,
            [ScanCode.KEY_KPMINUS] = 164,

            [ScanCode.KEY_TAB] = 168,
            [ScanCode.KEY_Q] = 172,
            [ScanCode.KEY_W] = 176,
            [ScanCode.KEY_E] = 180,
            [ScanCode.KEY_R] = 184,
            [ScanCode.KEY_T] = 188,
            [ScanCode.KEY_Y] = 192,
            [ScanCode.KEY_U] = 196,
            [ScanCode.KEY_I] = 200,
            [ScanCode.KEY_O] = 204,
            [ScanCode.KEY_P] = 208,
            [ScanCode.KEY_LEFTBRACE] = 212,
            [ScanCode.KEY_RIGHTBRACE] = 216,
            [ScanCode.KEY_BACKSLASH] = 220,
            [ScanCode.KEY_DELETE] = 224,
            [ScanCode.KEY_END] = 228,
            [ScanCode.KEY_PAGEDOWN] = 232,
            [ScanCode.KEY_KP7] = 236,
            [ScanCode.KEY_KP8] = 240,
            [ScanCode.KEY_KP9] = 244,
            [ScanCode.KEY_KPPLUS] = 248,

            [ScanCode.KEY_CAPSLOCK] = 252,
            [ScanCode.KEY_A] = 256,
            [ScanCode.KEY_S] = 260,
            [ScanCode.KEY_D] = 264,
            [ScanCode.KEY_F] = 268,
            [ScanCode.KEY_G] = 272,
            [ScanCode.KEY_H] = 276,
            [ScanCode.KEY_J] = 280,
            [ScanCode.KEY_K] = 284,
            [ScanCode.KEY_L] = 288,
            [ScanCode.KEY_SEMICOLON] = 292,
            [ScanCode.KEY_APOSTROPHE] = 296,
            [ScanCode.KEY_HASHTILDE] = 300,
            [ScanCode.KEY_ENTER] = 304,
            [ScanCode.KEY_KP4] = 320,
            [ScanCode.KEY_KP5] = 324,
            [ScanCode.KEY_KP6] = 328,

            [ScanCode.KEY_LEFTSHIFT] = 336,
            [ScanCode.KEY_102ND] = 340,
            [ScanCode.KEY_Z] = 344,
            [ScanCode.KEY_X] = 348,
            [ScanCode.KEY_C] = 352,
            [ScanCode.KEY_V] = 356,
            [ScanCode.KEY_B] = 360,
            [ScanCode.KEY_N] = 364,
            [ScanCode.KEY_M] = 368,
            [ScanCode.KEY_COMMA] = 372,
            [ScanCode.KEY_DOT] = 376,
            [ScanCode.KEY_SLASH] = 380,
            //
            [ScanCode.KEY_RIGHTSHIFT] = 388,
            //
            [ScanCode.KEY_UP] = 396,
            [ScanCode.KEY_KP1] = 404,
            [ScanCode.KEY_KP2] = 408,
            [ScanCode.KEY_KP3] = 412,
            [ScanCode.KEY_KPENTER] = 416,

            [ScanCode.KEY_LEFTCTRL] = 420,
            [ScanCode.KEY_LEFTMETA] = 424,
            [ScanCode.KEY_LEFTALT] = 428,
            [ScanCode.KEY_SPACE] = 440,
            [ScanCode.KEY_RIGHTALT] = 464,
            [ScanCode.KEY_RIGHTMETA] = 468,
            [ScanCode.KEY_RIGHTCTRL] = 476,
            [ScanCode.KEY_LEFT] = 480,
            [ScanCode.KEY_DOWN] = 484,
            [ScanCode.KEY_RIGHT] = 488,
            [ScanCode.KEY_KPDOT] = 492,
            [ScanCode.KEY_KP0] = 496
        };
    }
}
